#!/usr/bin/env node

/*! Copyright Twitter Inc. and other contributors. Licensed under MIT *//*
    https://github.com/twitter/twemoji/blob/gh-pages/LICENSE
*/

/*! msemoji is modified from twemoji by DaleZ(zDaleZ). Licensed inherits Twemoji. */

const fs = require('fs-extra');
const path = require('path');
const { spawnSync } = require('child_process');
const { getIntegrityHash } = require('./utils');

function file(...which) {
  return path.join(__dirname, '..', ...which);
}

function distFile(...which) {
  return path.join(__dirname, '..', 'dist', ...which);
}

const copyright = '/* Copyright Twitter Inc. and other contributors. Licensed under MIT */';
const addition = '/* msemoji is modified from twemoji by DaleZ(zDaleZ). Licensed inherits Twemoji. */';
const Contents = fs.readFileSync(distFile('msemoji.js'));

fs.writeFileSync(distFile('msemoji.esm.js'), `${copyright}\n${addition}\n${Contents}\nexport default msemoji;`);

spawnSync(
  'yarn',
  [
    'rollup',
    '-i',
    distFile('msemoji.esm.js'),
    '--format',
    'umd',
    '--name',
    'msemoji',
    '-o',
    distFile('msemoji.umd.js')
  ],
  {
    shell: process.platform === 'win32',
    stdio: 'inherit'
  }
);

spawnSync(
  'yarn',
  [
    'terser',
    distFile('msemoji.umd.js'),
    '--compress',
    '--verbose',
    '-o',
    distFile('msemoji.umd.min.js')
  ],
  {
    shell: process.platform === 'win32',
    stdio: 'inherit'
  }
);

spawnSync(
  'yarn',
  [
    'terser',
    distFile('msemoji.esm.js'),
    '--compress',
    '--verbose',
    '--module',
    '-o',
    distFile('msemoji.esm.min.js')
  ],
  {
    shell: process.platform === 'win32',
    stdio: 'inherit'
  }
);